FROM python:3.10-slim

# OS 
RUN apt-get update && apt-get install -y --no-install-recommends build-essential && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

#Install Python deps (CPU Torch)
COPY requirements.infer.txt /app/requirements.txt
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r /app/requirements.txt

COPY . /app

# Env vars (can override at docker run)
ENV PYTHONUNBUFFERED=1 \
    SCRAPS_CONFIG=/app/configs/train_small.yaml \
    SCRAPS_VOCAB=/app/tokenizer/bpe.json \
    SCRAPS_CKPT_DIR=/app/model/checkpoints \
    SCRAPS_PORT=8080


# Expose the FastAPI port
EXPOSE 8080

# Start the server
CMD ["uvicorn", "src.api.main:APP", "--host", "0.0.0.0", "--port", "8080"]
